-- Aplicada no projeto zybkcpvdptabxkxpieuv em 08/10/2026 (versão 20261008121631).
-- Verificado: anon não executa a função nem usa o esquema private; service_role executa; segredo de 64 chars.
--
-- Relatório mensal de saldo de férias (decisões do Asael em 08/10/2026):
-- vai para os líderes (só a equipe de cada um) + visão geral para Asael (id 1) e Fabio Storti Lago (id 116);
-- dia 1º às 8h (Brasília). Começa com envio de TESTE só para o Asael; o agendamento geral vem depois da aprovação.

-- Esquema privado: NÃO é exposto pela API (só public é). Guarda o segredo que protege a Edge Function.
CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;
CREATE TABLE private.config (chave text PRIMARY KEY, valor text NOT NULL);
-- Segredo aleatório gerado no próprio banco (ninguém precisa conhecê-lo; o agendamento lê daqui).
INSERT INTO private.config VALUES
  ('relatorio_ferias_segredo', replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')),
  -- Destinatários da visão geral por ID de usuário (o e-mail vem do cadastro e acompanha mudanças).
  ('relatorio_ferias_rh_ids', '1,116');

-- A função confere o segredo e devolve os destinatários. Só a service_role (Edge Function) executa.
CREATE OR REPLACE FUNCTION public.relatorio_ferias_config(p_segredo text)
RETURNS TABLE(rh_ids integer[])
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'private', 'public'
AS $$
BEGIN
  IF p_segredo IS NULL OR p_segredo IS DISTINCT FROM (SELECT valor FROM private.config WHERE chave = 'relatorio_ferias_segredo') THEN
    RAISE EXCEPTION 'não autorizado';
  END IF;
  RETURN QUERY SELECT string_to_array(valor, ',')::integer[] FROM private.config WHERE chave = 'relatorio_ferias_rh_ids';
END;
$$;
REVOKE ALL ON FUNCTION public.relatorio_ferias_config(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.relatorio_ferias_config(text) TO service_role;

-- Registro de cada execução (auditoria: quando rodou, quantos saíram, quais falharam).
CREATE TABLE public.relatorio_ferias_envios (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  executado_em timestamptz NOT NULL DEFAULT now(),
  modo         text NOT NULL,            -- teste | envio
  total        integer NOT NULL,
  enviados     integer NOT NULL,
  falhas       integer NOT NULL,
  detalhes     jsonb
);
ALTER TABLE public.relatorio_ferias_envios ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.relatorio_ferias_envios FROM anon, authenticated;  -- só a Edge Function grava/lê

-- Extensões para agendar (pg_cron) e chamar a função por HTTP (pg_net). Autorizado pelo Asael.
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
