-- Aplicada no projeto zybkcpvdptabxkxpieuv em 08/10/2026 (versão 20261008113830).
-- Testada como anon com rollback: importação válida grava; usuário não-RH é recusado; anon não grava direto.
--
-- Saldos de férias importados do relatório FPPF001 ("Relatório Coleta") da folha BRIT.
-- Por quê: a folha é a fonte da verdade dos saldos; o portal só exibe. O RH sobe o Excel todo mês.
-- Cada importação é uma "foto" completa; o portal usa sempre a mais recente. As antigas ficam como
-- histórico (são pequenas) — assim o navegador nunca precisa apagar nada.

CREATE TABLE public.ferias_importacoes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arquivo        text NOT NULL,
  data_relatorio date,                       -- data de emissão no rodapé do relatório
  importado_por  integer REFERENCES public.usuarios(id),
  importado_em   timestamptz NOT NULL DEFAULT now(),
  colaboradores  integer NOT NULL,
  periodos       integer NOT NULL
);

CREATE TABLE public.ferias_saldos (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacao_id  bigint NOT NULL REFERENCES public.ferias_importacoes(id) ON DELETE CASCADE,
  cadastro       text NOT NULL,
  nome           text NOT NULL,
  admissao       date,
  situacao       text,                       -- 1 = trabalhando, 2 = férias (códigos da folha)
  cargo          text,
  periodo_inicio date NOT NULL,
  periodo_fim    date NOT NULL,
  direito        numeric(5,2) NOT NULL,
  debito         numeric(5,2) NOT NULL,
  saldo          numeric(5,2) NOT NULL,
  sugestao       date                        -- coluna "Sugestão" da folha: último início para gozar o saldo no prazo
);
CREATE INDEX ferias_saldos_imp_cad_idx ON public.ferias_saldos (importacao_id, cadastro);

ALTER TABLE public.ferias_importacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ferias_saldos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ferias_importacoes, public.ferias_saldos FROM anon, authenticated;
-- O navegador só LÊ. Gravação apenas pela função abaixo (tudo-ou-nada).
GRANT SELECT ON public.ferias_importacoes, public.ferias_saldos TO anon, authenticated;
CREATE POLICY leitura ON public.ferias_importacoes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY leitura ON public.ferias_saldos FOR SELECT TO anon, authenticated USING (true);

-- Importa uma foto completa numa única transação. Valida o mínimo para não aceitar arquivo errado.
CREATE OR REPLACE FUNCTION public.importar_saldos_ferias(p_arquivo text, p_data_relatorio date, p_importado_por integer, p_linhas jsonb)
RETURNS TABLE(importacao_id bigint, colaboradores integer, periodos integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE v_id bigint; v_col integer; v_per integer;
BEGIN
  IF p_linhas IS NULL OR jsonb_typeof(p_linhas) <> 'array' OR jsonb_array_length(p_linhas) = 0 THEN
    RAISE EXCEPTION 'Nenhum período de férias no arquivo.';
  END IF;
  -- importado_por precisa ser RH ou dev ativo
  IF NOT EXISTS (SELECT 1 FROM usuarios WHERE id = p_importado_por AND role IN ('rh','dev') AND coalesce(status,'ativo')='ativo') THEN
    RAISE EXCEPTION 'Importação permitida apenas para RH.';
  END IF;
  SELECT count(DISTINCT l->>'cadastro'), count(*) INTO v_col, v_per FROM jsonb_array_elements(p_linhas) l;
  INSERT INTO ferias_importacoes (arquivo, data_relatorio, importado_por, colaboradores, periodos)
  VALUES (p_arquivo, p_data_relatorio, p_importado_por, v_col, v_per) RETURNING id INTO v_id;
  INSERT INTO ferias_saldos (importacao_id, cadastro, nome, admissao, situacao, cargo, periodo_inicio, periodo_fim, direito, debito, saldo, sugestao)
  SELECT v_id, l->>'cadastro', l->>'nome', (l->>'admissao')::date, l->>'situacao', l->>'cargo',
         (l->>'periodo_inicio')::date, (l->>'periodo_fim')::date,
         (l->>'direito')::numeric, (l->>'debito')::numeric, (l->>'saldo')::numeric, (l->>'sugestao')::date
  FROM jsonb_array_elements(p_linhas) l;
  RETURN QUERY SELECT v_id, v_col, v_per;
END;
$$;
REVOKE ALL ON FUNCTION public.importar_saldos_ferias(text,date,integer,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.importar_saldos_ferias(text,date,integer,jsonb) TO anon, authenticated;
