-- Aplicada no projeto zybkcpvdptabxkxpieuv em 07/10/2026 (versão 20261007165746).
--
-- Cursos e certificações do colaborador (Meu Perfil).
-- Por quê: a tela mostrava cursos fictícios fixos no código e o "+ Adicionar" não salvava nada.
-- A coluna usuarios.certs (text[]) só guarda o título; o formulário tem título, instituição e ano.
-- Decisão do Asael (07/10/2026): tabela própria, que depois serve de base para o módulo de
-- Treinamentos/NRs (aí entram campos como validade/carga horária — não criados agora de propósito).

CREATE TABLE public.cursos_usuarios (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  titulo      text NOT NULL CHECK (length(btrim(titulo)) > 0),
  instituicao text,
  ano         smallint CHECK (ano BETWEEN 1950 AND 2100),  -- ano de conclusão; opcional
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX cursos_usuarios_user_id_idx ON public.cursos_usuarios (user_id);

-- Permissões: mesmo modelo provisório do projeto enquanto não há Supabase Auth (o navegador é "anon").
-- Só leitura e inclusão: o front não edita nem apaga cursos, então não liberamos UPDATE/DELETE.
ALTER TABLE public.cursos_usuarios ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.cursos_usuarios FROM anon, authenticated;
GRANT SELECT, INSERT ON public.cursos_usuarios TO anon, authenticated;
CREATE POLICY cursos_leitura  ON public.cursos_usuarios FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY cursos_inclusao ON public.cursos_usuarios FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Preserva o que já existia em usuarios.certs (só títulos) para aparecer no perfil.
-- A coluna certs NÃO é alterada nem apagada.
INSERT INTO public.cursos_usuarios (user_id, titulo)
SELECT u.id, btrim(c) FROM public.usuarios u, unnest(u.certs) AS c
WHERE cardinality(u.certs) > 0 AND length(btrim(c)) > 0;
