-- Aplicada em 08/10/2026 (versão 20261008194011).
-- Verificado: anon não lê colaboradores_pis nem a coluna pis de ponto_batidas; lê horário e cadastro.
-- Dados carregados no mesmo dia (fora desta migration): 80 PIS (lista da Melina, todos com dígito verificador
-- válido) e 655 batidas dos 2 relógios (01–05/10/2026), conferidas por impressão digital contra os arquivos AFD.
--
-- Ponto eletrônico: PIS dos colaboradores + batidas importadas dos arquivos AFD dos relógios (REP).
-- Decisões do Asael (08/10/2026): espelho de ponto, banco de horas, alerta de batida faltando e horas extras.
-- Esta migration cria só a base (PIS + batidas + importação). Regras de jornada/banco de horas vêm depois.

-- PIS: dado pessoal. O navegador NÃO lê esta tabela; só funções do servidor (security definer) usam.
CREATE TABLE public.colaboradores_pis (
  cadastro      text PRIMARY KEY,               -- matrícula da folha BRIT
  nome          text NOT NULL,
  pis           char(12) NOT NULL UNIQUE,       -- como aparece no AFD (12 dígitos, zero à esquerda)
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.colaboradores_pis ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.colaboradores_pis FROM anon, authenticated;

CREATE TABLE public.ponto_importacoes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rep            text NOT NULL,                 -- nº de fabricação do relógio (cabeçalho do AFD)
  arquivo        text,
  periodo_inicio date,
  periodo_fim    date,
  gerado_em      timestamp,                     -- data/hora de geração no cabeçalho do AFD
  importado_por  integer REFERENCES public.usuarios(id),
  importado_em   timestamptz NOT NULL DEFAULT now(),
  batidas_arquivo integer NOT NULL,
  batidas_novas   integer NOT NULL,
  sem_dono        integer NOT NULL               -- batidas de PIS sem cadastro conhecido
);

-- Uma batida = (relógio, NSR). O NSR é único por relógio: reimportar ou importar períodos sobrepostos não duplica.
CREATE TABLE public.ponto_batidas (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rep           text NOT NULL,
  nsr           bigint NOT NULL,
  data_hora     timestamp NOT NULL,             -- hora local do relógio (sem fuso)
  cadastro      text,                           -- preenchido pelo PIS na importação; NULL se PIS desconhecido
  pis           char(12) NOT NULL,              -- guardado para religar depois, mas NÃO liberado ao navegador
  importacao_id bigint REFERENCES public.ponto_importacoes(id),
  UNIQUE (rep, nsr)
);
CREATE INDEX ponto_batidas_cad_data_idx ON public.ponto_batidas (cadastro, data_hora);

ALTER TABLE public.ponto_importacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ponto_batidas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ponto_importacoes, public.ponto_batidas FROM anon, authenticated;
GRANT SELECT ON public.ponto_importacoes TO anon, authenticated;
-- Batidas: o navegador lê tudo MENOS o PIS (permissão por coluna).
GRANT SELECT (id, rep, nsr, data_hora, cadastro, importacao_id) ON public.ponto_batidas TO anon, authenticated;
CREATE POLICY leitura ON public.ponto_importacoes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY leitura ON public.ponto_batidas FOR SELECT TO anon, authenticated USING (true);

-- Importa as batidas de um AFD (já lidas no navegador). Só RH/dev. Tudo-ou-nada. Liga PIS → cadastro aqui no servidor.
CREATE OR REPLACE FUNCTION public.importar_ponto_afd(p_arquivo text, p_rep text, p_periodo_inicio date, p_periodo_fim date,
  p_gerado_em timestamp, p_importado_por integer, p_batidas jsonb)
RETURNS TABLE(importacao_id bigint, batidas_arquivo integer, batidas_novas integer, repetidas integer, sem_dono integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE v_id bigint; v_total int; v_novas int; v_sem int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM usuarios WHERE id = p_importado_por AND role IN ('rh','dev') AND coalesce(status,'ativo')='ativo') THEN
    RAISE EXCEPTION 'Importação permitida apenas para RH.';
  END IF;
  IF p_batidas IS NULL OR jsonb_typeof(p_batidas) <> 'array' OR jsonb_array_length(p_batidas) = 0 THEN
    RAISE EXCEPTION 'Nenhuma batida no arquivo.';
  END IF;
  v_total := jsonb_array_length(p_batidas);
  INSERT INTO ponto_importacoes (rep, arquivo, periodo_inicio, periodo_fim, gerado_em, importado_por, batidas_arquivo, batidas_novas, sem_dono)
  VALUES (p_rep, p_arquivo, p_periodo_inicio, p_periodo_fim, p_gerado_em, p_importado_por, v_total, 0, 0) RETURNING id INTO v_id;
  WITH ins AS (
    INSERT INTO ponto_batidas (rep, nsr, data_hora, pis, cadastro, importacao_id)
    SELECT p_rep, (b->>'nsr')::bigint, (b->>'data_hora')::timestamp, b->>'pis', cp.cadastro, v_id
    FROM jsonb_array_elements(p_batidas) b LEFT JOIN colaboradores_pis cp ON cp.pis = b->>'pis'
    ON CONFLICT (rep, nsr) DO NOTHING
    RETURNING cadastro)
  SELECT count(*), count(*) FILTER (WHERE cadastro IS NULL) INTO v_novas, v_sem FROM ins;
  UPDATE ponto_importacoes SET batidas_novas = v_novas, sem_dono = v_sem WHERE id = v_id;
  RETURN QUERY SELECT v_id, v_total, v_novas, v_total - v_novas, v_sem;
END;
$$;
REVOKE ALL ON FUNCTION public.importar_ponto_afd(text,text,date,date,timestamp,integer,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.importar_ponto_afd(text,text,date,date,timestamp,integer,jsonb) TO anon, authenticated;
